service: serverless-preval

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-plugin-webpack
